# Your bot's login token, from discord.com/developers
bot token: 0000000000000000000000000000000000000
# The message to send, put [[mention]] where you want the mention for the f*cked user to be
message: 'Fuck you [[mention]]!'
# Guild ID, the id of the server the bot should use
guild: 0000000000000000000
# Moderation channel
moderation:
  000000000000:
    enabled: True
    channel: 0
